//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_clima
    {
        public int idDato { get; set; }
        public int idSensor { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<float> tempInt { get; set; }
        public Nullable<float> tempExt { get; set; }
        public Nullable<float> dewpoint { get; set; }
        public Nullable<byte> humedadInt { get; set; }
        public Nullable<byte> humedadExt { get; set; }
        public Nullable<float> vientoVel { get; set; }
        public Nullable<short> vientoGrados { get; set; }
        public string vientoDir { get; set; }
        public Nullable<float> sensacionTerm { get; set; }
        public Nullable<float> lluviaH { get; set; }
        public Nullable<float> lluviaD { get; set; }
        public Nullable<float> lluviaT { get; set; }
        public Nullable<float> presion { get; set; }
        public string tendencia { get; set; }
        public string pronostico { get; set; }
    
        public virtual Sensores Sensores { get; set; }
    }
}
