//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_energia
    {
        public int idDato { get; set; }
        public int idSensor { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<float> panelV { get; set; }
        public Nullable<float> panelC { get; set; }
        public Nullable<float> panelP { get; set; }
        public Nullable<float> charC { get; set; }
        public Nullable<float> charP { get; set; }
        public Nullable<float> charE { get; set; }
        public Nullable<float> charT { get; set; }
        public Nullable<float> batV { get; set; }
        public Nullable<float> batC { get; set; }
        public Nullable<float> batP { get; set; }
        public Nullable<float> batSOC { get; set; }
        public Nullable<float> batCE { get; set; }
        public Nullable<int> batTTG { get; set; }
        public Nullable<float> inv_inC { get; set; }
        public Nullable<float> inv_inP { get; set; }
        public Nullable<float> inv_outC { get; set; }
        public Nullable<float> inv_outP { get; set; }
        public Nullable<float> invE { get; set; }
    
        public virtual Sensores Sensores { get; set; }
    }
}
