//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Figuras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Figuras()
        {
            this.Sensores = new HashSet<Sensores>();
            this.Punto_de_Monitoreo = new HashSet<Punto_de_Monitoreo>();
        }
    
        public int idFigura { get; set; }
        public short tipo { get; set; }
        public string nombre { get; set; }
        public short size { get; set; }
        public string color { get; set; }
        public Nullable<short> borde { get; set; }
        public string colorBorde { get; set; }
        public Nullable<short> rotacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sensores> Sensores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Punto_de_Monitoreo> Punto_de_Monitoreo { get; set; }
    }
}
