//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imagenes()
        {
            this.Imagen_TipoSensor = new HashSet<Imagen_TipoSensor>();
            this.Marcadores = new HashSet<Marcadores>();
            this.MarcadoresMpz = new HashSet<MarcadoresMpz>();
        }
    
        public int idImagen { get; set; }
        public string nombre { get; set; }
        public Nullable<float> mx { get; set; }
        public Nullable<float> nx { get; set; }
        public Nullable<float> my { get; set; }
        public Nullable<float> ny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen_TipoSensor> Imagen_TipoSensor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marcadores> Marcadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarcadoresMpz> MarcadoresMpz { get; set; }
    }
}
