//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen_TipoSensor
    {
        public int idImagen { get; set; }
        public int idTipo { get; set; }
        public Nullable<byte> ordenar { get; set; }
    
        public virtual Imagenes Imagenes { get; set; }
        public virtual TipoSensores TipoSensores { get; set; }
    }
}
