//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marcadores
    {
        public int idSensor { get; set; }
        public int idImagen { get; set; }
        public short x { get; set; }
        public short y { get; set; }
    
        public virtual Imagenes Imagenes { get; set; }
        public virtual Sensores Sensores { get; set; }
    }
}
