//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseSpence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensores_Piezometros
    {
        public int idSensor { get; set; }
        public string seriePiezo { get; set; }
        public Nullable<float> profundidadPozo { get; set; }
        public Nullable<float> cotaTierra { get; set; }
        public Nullable<float> distT_A { get; set; }
        public Nullable<float> cotaAgua { get; set; }
        public Nullable<float> cotaSensor { get; set; }
        public Nullable<float> metrosSensor { get; set; }
        public Nullable<float> coefA { get; set; }
        public Nullable<float> coefB { get; set; }
        public Nullable<float> coefC { get; set; }
        public Nullable<float> tempK { get; set; }
        public Nullable<float> tempI { get; set; }
        public Nullable<int> freqRead { get; set; }
        public Nullable<int> freqSend { get; set; }
        public Nullable<float> baroI { get; set; }
        public Nullable<float> carpeta { get; set; }
    
        public virtual Sensores Sensores { get; set; }
    }
}
